eCommerce/Models/ErrorViewModel.cs
using System;

namespace eCommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

eCommerce/Models/ProductCategoryCreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace eCommerce.Models
{
    public class ProductCategoryCreateViewModel
    {
        [Required]
        public string Name { get; set; }

        public bool Active { get; set; }
    }
}

eCommerce/Models/ProductCategoryEditViewModel.cs
namespace eCommerce.Models
{
    public class ProductCategoryEditViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    }
}

eCommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using eCommerce.Models;
using MediatR;
using eCommerce.ApplicationServices.Commands;

namespace eCommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMediator _mediator;

        public HomeController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public IActionResult Index()
        {            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

eCommerce/Controllers/ProductCategoryController.cs
using eCommerce.ApplicationServices.Commands;
using eCommerce.ApplicationServices.Notifications;
using eCommerce.ApplicationServices.Queries;
using eCommerce.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eCommerce.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly IMediator _mediator;

        public ProductCategoryController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public IActionResult Index()
        {
            var categories = _mediator.Send(new ProductCategoryListQuery());            
            return View(categories.Result);
        }

        public IActionResult Add()
        {
            return View(new ProductCategoryCreateViewModel());
        }


        [HttpPost]
        public async Task<IActionResult> Add(ProductCategoryCreateViewModel viewModel)
        {            
            var result = await _mediator.Send(new ProductCategoryCreateCommand { Name = viewModel.Name });
            return RedirectToAction("Detail", new { id = result });
        }

        public IActionResult Edit(int id)
        {
            _mediator.Publish(new OrderPlacedNotification());

            var category = _mediator.Send(new ProductCategoryDetailQuery { Id = id }).Result;
            return View(new ProductCategoryEditViewModel
            {
                Id = category.Id,
                Name = category.Name,
                Active = category.Active
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductCategoryEditViewModel viewModel)
        {
            var category = await _mediator.Send(new ProductCategoryUpdateCommand
            {
                Id = viewModel.Id,
                Name = viewModel.Name,
                Active = viewModel.Active
            });

            return RedirectToAction("Detail", new { id = viewModel.Id });
        }

        public async Task<IActionResult> Detail(int id)
        {
            var detailModel = await _mediator.Send(new ProductCategoryDetailQuery { Id = id });
            return View(detailModel);
        }
    }
}

eCommerce/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace eCommerce.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

eCommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Folks!</h1>
    <p>Lets jump into a quick tour on CQRS and its implementation using MediatR</a>.</p>
</div>

eCommerce/Views/ProductCategory/Add.cshtml
@model eCommerce.Models.ProductCategoryCreateViewModel
@{
    ViewData["Title"] = "Add";
}

<h3>Add Product Category</h3>
<br />
@using (Html.BeginForm(FormMethod.Post, new { }))
{
<div class="form">
    <div class="form-group row">
        <label class="col-form-label col-sm-2">Name</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="form-group row">
        <label class="col-form-label col-sm-2">Active</label>
        <div class="col-sm-10">
            @Html.EditorFor(model => model.Active, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12" style="text-align:right;">
            <button type="submit" class="btn btn-primary">Submit</button>
            @Html.ActionLink("Cancel", "Index", new { }, new { @class="btn btn-secondary" })
        </div>
    </div>
</div>
}

eCommerce/Views/ProductCategory/Detail.cshtml
@using eCommerce.ApplicationServices.Dto

@model ProductCategoryDetailModel

@{
    ViewData["Title"] = "Detail";
}

<h3>Product Category Detail</h3>
<br />

<div class="form">
    <div class="form-group row">
        <label class="col-form-label col-sm-2">Name</label>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.Name, new { @class = "form-control-plaintext" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="form-group row">
        <label class="col-form-label col-sm-2">Active</label>
        <div class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12" style="text-align:right;">
            @Html.ActionLink("Edit", "Edit", new { id= Model.Id }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>

eCommerce/Views/ProductCategory/Edit.cshtml
@model eCommerce.Models.ProductCategoryEditViewModel
@{
    ViewData["Title"] = "Edit";
}

<h3>Edit Product Category</h3>
<br />
@using (Html.BeginForm(FormMethod.Post, new { }))
{
    <div class="form">
        <div class="form-group row">
            <label class="col-form-label col-sm-2">Name</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group row">
            <label class="col-form-label col-sm-2">Active</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Active)
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-12" style="text-align:right;">
                <button type="submit" class="btn btn-primary">Submit</button>
                @Html.ActionLink("Cancel", "Index", new { }, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

eCommerce/Views/ProductCategory/Index.cshtml
@using eCommerce.ApplicationServices.Dto

@model IEnumerable<ProductCategoryDetailModel>

@{
    ViewData["Title"] = "Index";
}

<h3>Product Categories</h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Active</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>@item.Name</td>
            <td>@Html.DisplayFor(model => item.Active)</td>
            <td>
                @Html.ActionLink("View", "Detail", new { id = item.Id })
            </td>
        </tr>
        }        
    </tbody>
</table>

@Html.ActionLink("Add New", "Add", new { }, new { @class="btn btn-primary btn" })

eCommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eCommerce</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eCommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductCategory" asp-action="Index">Product Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - eCommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>